### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by humblehacker** [objcio/keychain-item#1]
Thanks for producing this.  Could you add a license file?

**Comment by st3fan** [comment]
I have the same request. Without a license it is hard to either contribute or to use this code in a bigger project. My suggestion would be the MIT License, which is simple and liberal and commonly used by packages similar to this one.

cc @chriseidhof

**Comment by chriseidhof** [comment]
Oh, sorry! I only saw this now (I don't know of a way to automatically watch all repositories for our org).

**Comment by chriseidhof** [comment]
License added, thanks for letting us know!
